name: Cypress & Jest Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Upgrade npm 🎉
              run: npm i -g npm@latest
            - name: Install dependencies
              uses: actions/checkout@v2
              run: npm install
    cypress-run:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Restore npm dependencies
              uses: actions/cache@v2
              id: npm-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm run dev
              env:
                  VITE_HORIZON_NETWORK_PASSPHRASE: Test SDF Network ; September 2015
                  CYPRESS_SIMPLE_SIGNER_PRIVATE_KEY: ${{ secrets.SIMPLE_SIGNER_PRIVATE_KEY }}
    test:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 16
            - name: Restore npm dependencies
              uses: actions/cache@v2
              id: npm-cache
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Run the tests
              run: |
                  npm install
                  npm run test
    build-and-deploy:
        needs: [cypress-run, test]
        if: ${{ github.ref_name == 'main' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
            - name: Install and Build
              run: |
                  npm install
                  npm run build
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: dist
